spring:
  datasource:
    url: 
    username: root
    password: Neha@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

